### PR TITLE
Task/review template bugs

### LINKED ISSUE #2: Opinion Scale showing multiple when we go back and forth
image

### LINKED ISSUE #3: Internal Server Error when Creating a new Review
image

### LINKED ISSUE #4: Preview Answer Page:   Show all question and its answers in one page (like a template previews)
image

### LINKED ISSUE #5: Disable Future months
image

### PR DESCRIPTION
**Pull request by zasyadev**
#5 Fixed

### CODE REVIEW

File: component/Applaud/AllAplaud.jsx [hunk 1]
```diff
@@ -77,6 +77,10 @@ function AllAplaud({ user }) {
 
     [filterByUserId, allOrgApplaud]
   );
+  const disabledDate = (current) => {
```
Comment (zasyadev) [inline component/Applaud/AllAplaud.jsx]: Create a date helper file and move all duplicate code related to dates and use them in components

File: component/Applaud/AllAplaud.jsx [hunk 2]
```diff
@@ -91,6 +95,7 @@ function AllAplaud({ user }) {
               format="MMMM"
```
Comment (zasyadev) [inline component/Applaud/AllAplaud.jsx]: move all date formats in date helper file
