### PR TITLE
Task/review template bugs  and toggle button changes 

### LINKED ISSUE #10: Show Select Box instead of Toggle button in mobile
image

image
Make a common Toggle component for this and remove all duplicated code from files

### PR DESCRIPTION
**Pull request by zasyadev**

### CODE REVIEW

File: component/Review/ReceivedReviewComponent.jsx [hunk 1]
```diff
@@ -96,40 +97,33 @@ function ReceivedReviewComponent({ user, reviewId }) {
...
+          </Link>
+          <p className="text-lg font-bold text-red-400 mt-5">
+            Already Submitted This Review
+          </p>
         </div>
       ) : (
-        <Form layout="vertical" className="py-4" form={answerForm}>
+        <Form layout="vertical" className="py-4 w-11/12" form={answerForm}>
           <AnimatePresence>
             {questions ? (
```
Comment (zasyadev) [inline component/Review/ReceivedReviewComponent.jsx]: Change all logic where you are checking data and its length 

you can do` Number(data?.length) > 0`

File: component/Review/formhelper/FormSlideComponent.jsx [hunk 2]
```diff
@@ -76,229 +81,260 @@ export function FormSlideComponent({
...
-                <Input
-                  size="large"
-                  placeholder={type == "input" ? "Short Text" : ""}
+                <Radio.Group
                   onChange={(e) => {
+                    handleAnswerChange(id, e.target.value, "input_box");
+
                     answerHandle(id, e.target.value);
-                    handleAnswerChange(id, e.target.value);
-                    handleInputLimit(id, e.target.value);
```
Comment (zasyadev) [inline component/Review/formhelper/FormSlideComponent.jsx:138]: Why this is removed?

File: component/Review/formhelper/FormSlideComponent.jsx [hunk 3]
```diff
@@ -76,229 +81,260 @@ export function FormSlideComponent({
...
-                  maxLength={180}
-                />
+                  className="w-full h-full "
+                  required={true}
+                  size="large"
+                >
+                  <Row gutter={[32, 32]} justify="center">
+                    {options?.map((op, j) => {
+                      return (
+                        <Col xs={24} md={12} lg={8} key={j + "option"}>
```
Comment (zasyadev) [inline component/Review/formhelper/FormSlideComponent.jsx]: Why you are using index for the key , you can use any attribute that is different for all .
And also remove return if its a single statement

File: component/Review/formhelper/FormSlideComponent.jsx [hunk 4]
```diff
@@ -76,229 +81,260 @@ export function FormSlideComponent({
...
-                rows={4}
-                onChange={(e) => {
-                  handleAnswerChange(id, e.target.value);
-                  answerHandle(id, e.target.value);
-                }}
-              />
-            </Form.Item>
-          )}
+            )}
+            {type == "input" && (
```
Comment (zasyadev) [inline component/Review/formhelper/FormSlideComponent.jsx]: Why `"input"` is hardcoded ?

File: component/Review/formhelper/FormSlideComponent.jsx [hunk 5]
```diff
@@ -76,229 +81,260 @@ export function FormSlideComponent({
...
-              rules={[
-                {
-                  required: true,
-                  message: "",
-                },
-              ]}
-            >
-              <div className="question-view-rating">
-                <Rate
+            {type === "textarea" && (
```
Comment (zasyadev) [inline component/Review/formhelper/FormSlideComponent.jsx]: same question why `"textarea"` hardcoded ?

File: component/Review/formhelper/FormSlideComponent.jsx [hunk 6]
```diff
@@ -76,229 +81,260 @@ export function FormSlideComponent({
...
-            >
-              <Radio.Group
-                onChange={(e) => {
-                  handleAnswerChange(id, e.target.value);
-                  answerHandle(id, e.target.value);
-                }}
-                size="large"
-                className="w-full  "
+            )}
+            {type === "yesno" && (
```
Comment (zasyadev) [inline component/Review/formhelper/FormSlideComponent.jsx]: hardcoded ? same question ^^

File: component/Review/formhelper/FormSlideComponent.jsx [hunk 7]
```diff
@@ -76,229 +81,260 @@ export function FormSlideComponent({
...
+                  }
+                  okText="Yes"
+                  cancelText="No"
+                  onConfirm={() => handleSubmit()}
+                  placement="topRight"
+                  overlayClassName="max-w-sm"
+                >
+                  <PrimaryButton
+                    title={"Submit"}
+                    // loading={loadingSpin}
```
Comment (zasyadev) [inline component/Review/formhelper/FormSlideComponent.jsx]: Why these lines are commented?
