### PR TITLE
email template changes

### LINKED ISSUE #12: Email Template Issues
- Remove the unsubscribe button if it's not working or make it functional

- Change the Email template design. Follow the other websites' email templates
- User name must be large and bold 
- remove all useless information if it's not required

image

### PR DESCRIPTION
**Pull request by zasyadev**

### CODE REVIEW

File: pages/api/user/index.js [hunk 1]
```diff
@@ -72,9 +72,13 @@ async function handle(req, res, prisma) {
       from: process.env.SMTP_USER,
       to: transactionData.savedData.email,
       subject: `Successfully Registered on Zasya Review App`,
-      html: mailTemplate(
-        `You have successfull registered on Review App . Please <a href= ${process.env.NEXT_APP_URL}/auth/login>Login</a> in to continue with your Profile.`
-      ),
+
+      html: mailTemplate({
+        body: `You have successfull registered on Review App. Please login to get started.`,
```
Comment (kshitijzasya) [inline pages/api/user/index.js]: successfull ?

Comment (zasyadev) [reply pages/api/user/index.js]: done successfully
